image: python:3.12-slim

pipelines:
    tags:
      v*:
        - step:
           script:
             - apt update
             - apt install -y git
             - git remote add sync git@github.com:miyabilink/sukkiri-python2-codes.git
             - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
             - git fetch origin
             - git checkout main
             - git pull
             - git merge origin/main
             - git rm -f bitbucket-pipelines.yml
             - git commit -m “不要なファイルの削除”
             - apt install -y gcc python3-dev 
             - apt install -y jupyter-core jupyter-nbconvert
             - pip install --upgrade pip
             - pip3 install jupyter
             - jupyter nbconvert --to script ipynb/*.ipynb
             - mkdir py && mv ipynb/*.py py && ls py
             - git add py && git tag -d $BITBUCKET_TAG && git commit -m '最新コードに関して、ipynb形式からpy形式への変換' && git tag $BITBUCKET_TAG
             - git filter-branch -f --env-filter "GIT_AUTHOR_NAME='Shinpei KUDO'; GIT_AUTHOR_EMAIL='kudo@miyabilink.jp'; GIT_COMMITTER_NAME='Shinpei KUDO'; GIT_COMMITTER_EMAIL='kudo@miyabilink.jp';" --tag-name-filter cat -- --all
             - git push sync --tags
             - git push -f sync main
